### ISSUE TITLE
你好！这里排版出现了大量重复内容。

### ISSUE THREAD

**Issue by comeCU** [Snailclimb/Java-Guide#16]
Here --> [面试必备/程序员的简历之道.md](https://github.com/Snailclimb/Java-Guide/blob/master/%E9%9D%A2%E8%AF%95%E5%BF%85%E5%A4%87/%E7%A8%8B%E5%BA%8F%E5%91%98%E7%9A%84%E7%AE%80%E5%8E%86%E4%B9%8B%E9%81%93.md)

**Comment by Snailclimb** [comment]
感谢提醒！已经修复。
